export const keyCodes: Object = {
  0: 'NUMPAD0',
  1: 'NUMPAD1',
  2: 'NUMPAD2',
  3: 'NUMPAD3',
  4: 'NUMPAD4',
  5: 'NUMPAD5',
  6: 'NUMPAD6',
  7: 'NUMPAD7',
  8: 'NUMPAD8',
  9: 'NUMPAD9',
  backspace: 'BACK_SPACE',
  tab: 'TAB',
  enter: 'ENTER',
  shift: 'SHIFT',
  ctrl: 'CONTROL',
  alt: 'ALT',
  pause_break: 'PAUSE',
  // caps_lock: 20,
  escape: 'ESCAPE',
  page_up: 'PAGE_UP',
  page_down: 'PAGE_DOWN',
  end: 'END',
  home: 'HOME',
  left_arrow: 'ARROW_LEFT',
  up_arrow: 'ARROW_UP',
  right_arrow: 'ARROW_RIGHT',
  down_arrow: 'ARROW_DOWN',
  insert: 'INSERT',
  delete: 'DELETE',
  left_window_key: 91,
  right_window_key: 92,
  select_key: 93,
  numpad_0: 'NUMPAD0',
  numpad_1: 'NUMPAD1',
  numpad_2: 'NUMPAD2',
  numpad_3: 'NUMPAD3',
  numpad_4: 'NUMPAD4',
  numpad_5: 'NUMPAD5',
  numpad_6: 'NUMPAD6',
  numpad_7: 'NUMPAD7',
  numpad_8: 'NUMPAD8',
  numpad_9: 'NUMPAD9',
  multiply: 'MULTIPLY',
  add: 'ADD',
  subtract: 'SUBTRACT',
  decimal_point: 'DECIMAL',
  divide: 'DIVIDE',
  f1: 'F1',
  f2: 'F2',
  f3: 'F3',
  f4: 'F4',
  f5: 'F5',
  f6: 'F6',
  f7: 'F7',
  f8: 'F8',
  f9: 'F9',
  f10: 'F10',
  f11: 'F11',
  f12: 'F12',
  // num_lock: 144,
  // scroll_lock: 145,
  semi_colon: 'SEMICOLON',
  equal_sign: 'EQUALS',
  // comma: 188,
  // dash: 189,
  // period: 190,
  // forward_slash: 191,
  // grave_accent: 192,
  // open_bracket: 219,
  // back_slash: 220,
  // close_braket: 221,
  // single_quote: 222,
};
